name: Shell Commands
# イベントトリガー
on:
  push:
    branches:
      - 'master'

jobs:
  # job名(任意の名前で良い)
  run-shell-commmand:
    # virtual machineの形式を指定
    runs-on: ubuntu-latest
    # jobのステップ
    steps:
      # ステップ名
      - name: echo a string
        run: echo "Hello World"
      # ステップ2
      - name: multiline script
        run: | # 複数のコマンドを記載したいときは|(パイプ)で繋ぐ
          node -v
          npm -v